### ISSUE TITLE
Priority field in Snippet object breaks generic serde_json::from_str parsing

### ISSUE THREAD

**Issue by tlrmello** [fastly/fastly-rust#2]
**Version**

1.0.0-beta.0

**What happened**

The `Snippet` construct returned within the response to `GET /service/<sid>/details` (and presumably any other endpoint that returns a Snippet object within it's schema) has it's `Priority` and `Dynamic` fields returning as a String datatype, but it appears the `serde_json::from_str` thinks it should be an `i32`. It looks like we may need to specify explicit data types for all possible fields that can be returned from the API 😵‍💫 

https://github.com/fastly/fastly-rust/blob/main/src/apis/service_api.rs#L321

Response example:
```
"snippets": [
      {
        "name": "cacheable",
        "content": "if (beresp.status == 200) {\n  set beresp.ttl = 60s;\n  return(deliver);\n} else {\n  return(pass);\n}",
        "type": "fetch",
        "priority": "100",
        "id": "<redacted>",
        "dynamic": "0"
      },
```

Error: 
```
Err(
    Serde(
        Error("invalid type: string \"100\", expected i32", line: 1, column: 3148),
    ),
)
```

**Comment by Integralist** [comment]
I'm going to close this issue as I believe this was resolved in the 2.1.1 release back in May:
https://github.com/fastly/fastly-rust/blob/main/CHANGELOG.md#v211-2023-05-22
