### ISSUE TITLE
Missing support for PackageApi::upload_package

### ISSUE THREAD

**Issue by jannic** [fastly/fastly-rust#5]
**Version**

fastly-api = "1.1.0"

**What happened**

I wanted to upload a Compute@Edge package using the https://developer.fastly.com/reference/api/services/package/#put-package  API. However, it looks like that's not supported by fastly-api yet.

Is that intentional, or perhaps some limitation of the code generator?

There is the model struct `fastly_api::models::PackageUpload`, but that seems to be unused.

**Comment by Integralist** [comment]
The recent v3.0.0 release now has support for that endpoint.

https://github.com/fastly/fastly-rust/blob/main/CHANGELOG.md#v300-2023-07-06

So I'm going to close this issue.
